// movies.js
export const movies = [
   //testing data
  { title: "Before Sunrise", year: 1995, plot: "Two strangers meet on a train and spend one evening together in Vienna.", location: "Vienna", time: "evening", event: "chance encounter", characters: ["two strangers"] },
  { title: "Before Sunset", year: 2004, plot: "A couple reunites in Paris after many years, sharing one afternoon together.", location: "Paris", time: "afternoon", event: "reunion", characters: ["two strangers"] },
  { title: "La La Land", year: 2016, plot: "Two artists fall in love while chasing their dreams in Los Angeles.", location: "Los Angeles", time: "day", event: "romantic encounter", characters: ["two strangers"] },
  { title: "Amélie", year: 2001, plot: "A quirky girl tries to help others find happiness in Montmartre.", location: "Paris", time: "day", event: "random encounter", characters: ["strangers"] },
  { title: "Notting Hill", year: 1999, plot: "A bookstore owner meets a famous actress and they fall in love.", location: "London", time: "day", event: "accidental meeting", characters: ["two strangers"] },
  { title: "Love Actually", year: 2003, plot: "Multiple love stories unfold in London around Christmas.", location: "London", time: "day", event: "holiday encounter", characters: ["friends", "family"] },
  { title: "10 Things I Hate About You", year: 1999, plot: "High school romance sparks between two students.", location: "Seattle", time: "day", event: "school encounter", characters: ["students"] },
  { title: "Crazy Rich Asians", year: 2018, plot: "A woman meets her boyfriend’s ultra-rich family in Singapore.", location: "Singapore", time: "day", event: "family encounter", characters: ["two strangers", "family"] },
  { title: "Titanic", year: 1997, plot: "A young couple falls in love aboard a doomed ship.", location: "Atlantic Ocean", time: "day", event: "ship encounter", characters: ["two strangers"] },
  { title: "Her", year: 2013, plot: "A man falls in love with his AI operating system.", location: "Los Angeles", time: "day", event: "technology encounter", characters: ["man", "AI"] },
  { title: "500 Days of Summer", year: 2009, plot: "A man reflects on a past romantic relationship in Los Angeles.", location: "Los Angeles", time: "day", event: "reflection", characters: ["two strangers"] },
  //1950s
  { title: "Roman Holiday", year: 1953, plot: "A Princess escapes her palace to venture out in the real world to experience a sense of freedom while falling in love with an undercover american reporter.", location: "Rome", time:"day", event:"accidental metting", characters: ["two strangers"]},
  { title: "Sabrina", year: 1954, plot: "The chauffeur’s daughter returns from Paris transformed and meets the wealthy son of the family.", location: "Long Island", time: "day", event: "accidental meeting", characters: ["two strangers"] },
  { title: "Funny Face", year: 1957, plot: "A bookstore clerk meets a fashion photographer in Paris, leading to romance.", location: "Paris", time: "day", event: "workplace encounter", characters: ["two strangers"] },
  { title: "Desk Set", year: 1957, plot: "A research department head meets an efficiency expert who challenges her routines.", location: "New York City", time: "day", event: "workplace encounter", characters: ["coworkers"] },
  { title: "Gentlemen Prefer Blondes", year: 1953, plot: "Two showgirls meet wealthy men while traveling to Paris.", location: "Ship/Paris", time: "day", event: "travel encounter", characters: ["two strangers"] },
  { title: "The Seven year: Itch", year: 1955, plot: "A man meets his neighbor while his family is away, sparking fantasies and flirtation.", location: "New York City", time: "evening", event: "apartment encounter", characters: ["two strangers"] },
  { title: "Auntie Mame", year: 1958, plot: "A young man meets his eccentric aunt who changes his outlook on life.", location: "New York City", time: "day", event: "family encounter", characters: ["family"] },
  { title: "Love in the Afternoon", year: 1957, plot: "A young woman meets a wealthy American playboy in Paris.", location: "Paris", time: "day", event: "romantic encounter", characters: ["two strangers"] },
  { title: "The Philadelphia Story", year: 1950, plot: "A socialite’s wedding plans are interrupted when her ex-husband and a reporter arrive.", location: "Philadelphia", time: "day", event: "social encounter", characters: ["two strangers", "friends"] },
  { title: "All About Eve", year: 1950, plot: "An ambitious young woman meets an aging actress, leading to personal and professional entanglements.", location: "New York City", time: "day", event: "workplace encounter", characters: ["two strangers"] },
  { title: "Houseboat", year: 1958, plot: "A widower meets a spirited governess who brings chaos and love to his home.", location: "Rome", time: "day", event: "accidental meeting", characters: ["two strangers"] },
  { title: "That Touch of Mink", year: 1952, plot: "A man and woman meet on the street and navigate romance and social class.", location: "New York City", time: "day", event: "street encounter", characters: ["two strangers"] },
  { title: "Father of the Bride", year: 1950, plot: "A father meets his daughter’s fiancé and navigates comedic family dynamics.", location: "California", time: "day", event: "family encounter", characters: ["family"] },
  { title: "The Lady Eve", year: 1950, plot: "A conwoman meets a wealthy heir on a cruise and sparks romance.", location: "Cruise ship", time: "day", event: "travel encounter", characters: ["two strangers"] },
  { title: "High Society", year: 1956, plot: "A socialite reconnects with a former love while entertaining high-profile guests.", location: "Newport, Rhode Island", time: "day", event: "social encounter", characters: ["two strangers", "friends"] },
  { title: "Three Coins in the Fountain", year: 1954, plot: "Three American women meet Italian men while working in Rome.", location: "Rome", time: "day", event: "travel encounter", characters: ["two strangers"] },
  { title: "Picnic", year: 1955, plot: "A drifter meets a small-town woman during a festival.", location: "Kansas town", time: "day", event: "festival encounter", characters: ["two strangers"] },
  { title: "Rear Window", year: 1954, plot: "Though a thriller, a couple meets through neighborly observation, sparking romantic tension.", location: "New York City", time: "day", event: "apartment encounter", characters: ["two strangers"] },
  { title: "Blackboard Jungle", year: 1955, plot: "A teacher meets challenging students and forms bonds over conflict and mentorship.", location: "New York City", time: "day", event: "school encounter", characters: ["teacher", "students"] },
  { title: "Love Is a Many-Splendored Thing", year: 1955, plot: "A journalist meets a doctor in Hong Kong during a politically tense period.", location: "Hong Kong", time: "day", event: "professional encounter", characters: ["two strangers"] },
  { title: "The Courtship of Eddie's Father", year: 1956, plot: "A widower meets a spirited woman while navigating fatherhood.", location: "California", time: "day", event: "accidental meeting", characters: ["two strangers"] },
  { title: "Desk Set", year: 1957, plot: "Research department head meets efficiency consultant at work.", location: "New York City", time: "day", event: "workplace encounter", characters: ["coworkers"] },
  { title: "Pal Joey", year: 1957, plot: "A nightclub singer meets a wealthy woman leading to romance and deception.", location: "San Francisco", time: "night", event: "social encounter", characters: ["two strangers"] },
  { title: "The Tarnished Angels", year: 1957, plot: "Romantic tension arises between a journalist and a pilot’s wife.", location: "Mississippi", time: "day", event: "accidental meeting", characters: ["two strangers"] },
  { title: "Bell, Book and Candle", year: 1958, plot: "A witch meets her neighbor and casts a spell to make him fall in love.", location: "New York City", time: "day", event: "apartment encounter", characters: ["two strangers"] },
  { title: "Gigi", year: 1958, plot: "A young Parisian girl meets a wealthy playboy as she prepares for society debut.", location: "Paris", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "The Best Things in Life Are Free", year: 1956, plot: "Two songwriters meet during career pursuits in New York City.", location: "New York City", time: "day", event: "workplace encounter", characters: ["coworkers"] },
  { title: "April in Paris", year: 1952, plot: "A dancer and singer meet in Paris while touring.", location: "Paris", time: "day", event: "travel encounter", characters: ["two strangers"] },
  { title: "Lovely to Look At", year: 1952, plot: "A costume designer meets a wealthy man at a fashion event.", location: "New York City", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "We're No Angels", year: 1955, plot: "Two convicts meet a family while hiding from authorities, leading to comedy and romance.", location: "New York", time: "day", event: "accidental meeting", characters: ["two strangers", "family"] },

  // 1960s
  { title: "Breakfast at Tiffany's", year: 1961, plot: "A quirky socialite meets a struggling writer in New York.", location: "New York City", time: "day", event: "apartment encounter", characters: ["two strangers"] },
  { title: "The Apartment", year: 1960, plot: "A junior executive meets his neighbor after a dropped key mishap.", location: "New York City", time: "morning", event: "accidental meeting", characters: ["two strangers"] },
  { title: "Charade", year: 1963, plot: "A widow meets a mysterious stranger while uncovering her late husband's secrets.", location: "Paris", time: "day", event: "mystery encounter", characters: ["two strangers"] },
  { title: "That Touch of Mink", year: 1962, plot: "A businessman and a secretary meet by chance on the street, leading to romance.", location: "New York City", time: "day", event: "street encounter", characters: ["two strangers"] },
  { title: "My Fair Lady", year: 1964, plot: "A phonetics professor meets a flower girl to teach her how to speak properly.", location: "London", time: "day", event: "workplace encounter", characters: ["teacher", "student"] },
  { title: "How to Steal a Million", year: 1966, plot: "A woman meets a charming burglar to help cover up her father’s art forgery.", location: "Paris", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Barefoot in the Park", year: 1967, plot: "A newlywed couple navigates life and meets quirky neighbors.", location: "New York City", time: "day", event: "apartment encounter", characters: ["two strangers"] },
  { title: "Funny Girl", year: 1968, plot: "A performer meets a charming gambler and begins a tumultuous romance.", location: "New York City", time: "day", event: "workplace encounter", characters: ["two strangers"] },
  { title: "The Sound of Music", year: 1965, plot: "A governess meets a widowed naval officer while caring for his children.", location: "Salzburg", time: "day", event: "workplace encounter", characters: ["two strangers"] },
  { title: "Doctor Dolittle", year: 1967, plot: "A doctor meets animals and villagers while discovering his unique gift.", location: "England", time: "day", event: "community encounter", characters: ["two strangers", "community"] },
  { title: "The Pink Panther", year: 1963, plot: "A bumbling inspector meets a jewel thief while solving a high-profile case.", location: "Rome", time: "day", event: "accidental meeting", characters: ["two strangers"] },
  { title: "Goodbye Charlie", year: 1964, plot: "A man is reincarnated as a woman and meets friends unaware of the change.", location: "Los Angeles", time: "day", event: "identity encounter", characters: ["two strangers", "friends"] },
  { title: "A New Kind of Love", year: 1963, plot: "A fashion executive meets a rival at a Paris fashion show.", location: "Paris", time: "day", event: "workplace encounter", characters: ["coworkers"] },
  { title: "The Best of Everything", year: 1959, plot: "Young women meet colleagues and romantic interests at a publishing company.", location: "New York City", time: "day", event: "workplace encounter", characters: ["coworkers"] },
  { title: "Arabesque", year: 1966, plot: "A professor meets a mysterious woman while solving an espionage mystery.", location: "Istanbul", time: "day", event: "mystery encounter", characters: ["two strangers"] },
  { title: "The World of Henry Orient", year: 1964, plot: "Two schoolgirls meet a flamboyant pianist, inspiring teenage crushes.", location: "New York City", time: "day", event: "school encounter", characters: ["students"] },
  { title: "Promises! Promises!", year: 1963, plot: "A woman meets her ex-lover while juggling fame and romance.", location: "New York City", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "The Thrill of It All", year: 1963, plot: "A housewife meets a TV producer while being scouted for advertising work.", location: "New York City", time: "day", event: "workplace encounter", characters: ["two strangers"] },
  { title: "Move Over, Darling", year: 1963, plot: "A woman returns from amnesia and meets her husband, rekindling romance.", location: "New York City", time: "day", event: "reunion", characters: ["two strangers", "family"] },
  { title: "Father Goose", year: 1964, plot: "A beach recluse meets a schoolteacher during WWII, sparking romance.", location: "Pacific Island", time: "day", event: "accidental meeting", characters: ["two strangers"] },
  { title: "How to Murder Your Wife", year: 1965, plot: "A cartoonist meets his wife unexpectedly during a bachelor lifestyle.", location: "New York City", time: "day", event: "accidental meeting", characters: ["two strangers"] },
  { title: "That Man from Rio", year: 1964, plot: "A man meets a woman while chasing stolen artifacts, leading to adventure and romance.", location: "Rio de Janeiro", time: "day", event: "adventure encounter", characters: ["two strangers"] },
  { title: "The Gold of Naples", year: 1954, plot: "Various stories of love unfold in Naples with accidental romantic encounters.", location: "Naples", time: "day", event: "random encounter", characters: ["two strangers"] },
  { title: "Sons and Lovers", year: 1960, plot: "Romantic tension arises between young adults in a small community.", location: "England", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "The Unsinkable Molly Brown", year: 1964, plot: "A spirited woman meets a wealthy man and fights for acceptance and love.", location: "Colorado / Titanic", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "The Oscar", year: 1966, plot: "A rising actor meets people who influence his career and romantic life.", location: "Los Angeles", time: "day", event: "professional encounter", characters: ["two strangers", "coworkers"] },
  { title: "Paris When It Sizzles", year: 1964, plot: "A screenwriter meets a secretary while completing a romantic screenplay.", location: "Paris", time: "day", event: "workplace encounter", characters: ["coworkers"] },
  { title: "The Pink Panther", year: 1963, plot: "Inspector Clouseau meets a jewel thief in Paris, sparking comedic romantic tension.", location: "Paris", time: "day", event: "accidental meeting", characters: ["two strangers"] },

  //1970s
  { title: "Annie Hall", year: 1977, plot: "A neurotic comedian meets a quirky singer-songwriter at a comedy club.", location: "New York City", time: "evening", event: "social encounter", characters: ["two strangers"] },
  { title: "Sleeper", year: 1973, plot: "A man wakes 200 years in the future and meets a woman in a futuristic city.", location: "Futuristic city", time: "day", event: "accidental meeting", characters: ["two strangers"] },
  { title: "The Goodbye Girl", year: 1977, plot: "A divorced couple reunites by chance while attending a wedding.", location: "Los Angeles", time: "day", event: "reunion", characters: ["two strangers"] },
  { title: "Manhattan", year: 1976, plot: "A small-town man meets a big-city woman, sparking romance and a clash of lifestyles.", location: "New York City", time: "day", event: "street encounter", characters: ["two strangers"] },
  { title: "Nickelodeon", year: 1976, plot: "Two people meet while stranded during a cross-country road trip, forming an unexpected bond.", location: "Midwest USA", time: "day", event: "road trip encounter", characters: ["two strangers"] },
  { title: "The Rose", year: 1979, plot: "A struggling musician meets a woman during a chance encounter at a nightclub.", location: "New York City", time: "night", event: "social encounter", characters: ["two strangers"] },
  { title: "A Little Romance", year: 1979, plot: "Two young travelers meet while exploring Europe.", location: "Europe", time: "day", event: "travel encounter", characters: ["two strangers"] },
  { title: "Neighbors", year: 1971, plot: "Two neighbors become friends after a series of misunderstandings, slowly falling in love.", location: "Suburban neighborhood", time: "day", event: "apartment encounter", characters: ["two strangers"] },
  { title: "The Omega Man", year: 1971, plot: "A man meets a woman at a political rally, leading to romance and personal growth.", location: "Washington D.C.", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Slap Shot", year: 1977, plot: "Two people meet during a minor-league hockey game, sparking humor and romance.", location: "Small town, USA", time: "day", event: "sport encounter", characters: ["two strangers"] },
  { title: "The Goodbye Girl", year: 1977, plot: "A woman meets a man while sharing an apartment after a broken engagement.", location: "New York City", time: "day", event: "apartment encounter", characters: ["two strangers"] },
  { title: "Love and Death", year: 1975, plot: "A timid man meets a woman during a philosophical debate, leading to romantic misadventures.", location: "Russia", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "The Other Side of Midnight", year: 1977, plot: "Two lovers meet again under dramatic circumstances in Europe.", location: "Paris / Rome", time: "day", event: "reunion", characters: ["two strangers"] },
  { title: "Network", year: 1976, plot: "A reporter meets a woman during a broadcast, sparking a brief but meaningful romance.", location: "New York City", time: "day", event: "professional encounter", characters: ["two strangers"] },
  { title: "Marathon Man", year: 1976, plot: "A graduate student meets a mysterious woman while traveling for research.", location: "New York City", time: "day", event: "travel encounter", characters: ["two strangers"] },
  { title: "The Little Girl Who Lives Down the Lane", year: 1976, plot: "A young girl meets a stranger who changes her life.", location: "Small town, USA", time: "day", event: "accidental meeting", characters: ["two strangers"] },
  { title: "The Choirboys", year: 1977, plot: "Two men meet by chance while patrolling the city, forming a quirky bond.", location: "Los Angeles", time: "night", event: "workplace encounter", characters: ["coworkers"] },
  { title: "The Man Who Fell to Earth", year: 1976, plot: "An alien meets a woman on Earth, sparking curiosity and romance.", location: "New York City", time: "day", event: "accidental meeting", characters: ["two strangers"] },
  { title: "The Last Tycoon", year: 1976, plot: "A film producer meets a woman on set, beginning a romantic subplot.", location: "Hollywood", time: "day", event: "workplace encounter", characters: ["two strangers"] },
  { title: "The Seven-Ups", year: 1973, plot: "Two detectives meet while chasing criminals, sparking flirtation.", location: "New York City", time: "day", event: "professional encounter", characters: ["coworkers"] },
  { title: "The End of the World", year: 1977, plot: "A woman meets a man during a citywide crisis, leading to romance.", location: "Los Angeles", time: "day", event: "public encounter", characters: ["two strangers"] },
  { title: "Rollercoaster", year: 1977, plot: "A couple meets while on a rollercoaster ride at an amusement park.", location: "Orlando", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "The Domino Principle", year: 1977, plot: "A man meets a woman while being caught in espionage, forming an unexpected bond.", location: "New York City", time: "day", event: "adventure encounter", characters: ["two strangers"] },
  { title: "Fun with Dick and Jane", year: 1977, plot: "A couple meets during corporate chaos and finds love amid comedy.", location: "Los Angeles", time: "day", event: "workplace encounter", characters: ["two strangers"] },
  { title: "Capricorn One", year: 1978, plot: "A journalist meets a woman while uncovering a conspiracy.", location: "Washington D.C.", time: "day", event: "professional encounter", characters: ["two strangers"] },
  { title: "Time After Time", year: 1979, plot: "A man meets a woman while traveling through time, leading to romance.", location: "San Francisco", time: "day", event: "travel encounter", characters: ["two strangers"] },
  { title: "Being There", year: 1979, plot: "A simple gardener meets a wealthy woman, leading to social comedy and romance.", location: "Washington D.C.", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "1941", year: 1979, plot: "A man and woman meet during chaotic wartime events, forming unexpected connections.", location: "Los Angeles", time: "day", event: "public encounter", characters: ["two strangers"] },

  //1980s
  { title: "When Harry Met Sally...", year: 1989, plot: "Two friends meet on a road trip and debate whether men and women can be friends.", location: "Chicago / New York City", time: "day", event: "road trip encounter", characters: ["two strangers"] },
  { title: "Moonstruck", year: 1987, plot: "A woman meets her fiancé’s brother at a family dinner and sparks fly.", location: "Brooklyn", time: "evening", event: "family encounter", characters: ["two strangers", "family"] },
  { title: "Working Girl", year: 1988, plot: "A secretary meets her boss while planning a corporate merger, leading to romance.", location: "New York City", time: "day", event: "workplace encounter", characters: ["coworkers"] },
  { title: "Loverboy", year: 1989, plot: "A man and woman meet while stuck in a traffic jam, leading to unexpected chemistry.", location: "Los Angeles", time: "day", event: "public encounter", characters: ["two strangers"] },
  { title: "Broadcast News", year: 1987, plot: "Two coworkers meet during a high-stakes news pitch, sparking romance.", location: "Washington D.C.", time: "day", event: "workplace encounter", characters: ["coworkers"] },
  { title: "Heartburn", year: 1986, plot: "A man meets a woman after crashing his car into hers, beginning a quirky romance.", location: "New York City", time: "day", event: "accidental meeting", characters: ["two strangers"] },
  { title: "A Room with a View", year: 1985, plot: "Two travelers meet in Florence and experience unexpected romance.", location: "Florence, Italy", time: "day", event: "travel encounter", characters: ["two strangers"] },
  { title: "Tootsie", year: 1982, plot: "A man disguises himself as a woman and meets a co-star on set.", location: "New York City", time: "day", event: "workplace encounter", characters: ["coworkers"] },
  { title: "Sixteen Candles", year: 1984, plot: "A teenage girl meets a popular boy in school, sparking adolescent romance.", location: "Suburban Chicago", time: "day", event: "school encounter", characters: ["students"] },
  { title: "Blame It on Rio", year: 1984, plot: "Two men meet a young woman during a vacation in Rio, leading to comedic romance.", location: "Rio de Janeiro", time: "day", event: "travel encounter", characters: ["two strangers"] },
  { title: "Big", year: 1988, plot: "A boy turned man meets a woman while working in a toy company.", location: "New York City", time: "day", event: "workplace encounter", characters: ["two strangers"] },
  { title: "Roxanne", year: 1987, plot: "A fire chief meets a witty woman in his town, sparking romance.", location: "Small town, USA", time: "day", event: "public encounter", characters: ["two strangers"] },
  { title: "Crossing Delancey", year: 1988, plot: "A woman meets a pickle vendor through a matchmaker, leading to romance.", location: "New York City", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Broadcast News", year: 1987, plot: "A reporter and producer meet during newsroom chaos, leading to romantic tension.", location: "Washington D.C.", time: "day", event: "workplace encounter", characters: ["coworkers"] },
  { title: "The Secret of My Success", year: 1987, plot: "A young man meets his boss while climbing the corporate ladder.", location: "New York City", time: "day", event: "workplace encounter", characters: ["coworkers"] },
  { title: "Fast Times at Ridgemont High", year: 1982, plot: "High school students meet and navigate young romance.", location: "California", time: "day", event: "school encounter", characters: ["students"] },
  { title: "Footloose", year: 1984, plot: "A teenager meets a local girl in a small town while challenging social rules.", location: "Small town, USA", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Romancing the Stone", year: 1984, plot: "A writer meets an adventurer while on a treasure hunt in Colombia.", location: "Colombia", time: "day", event: "adventure encounter", characters: ["two strangers"] },
  { title: "The Big Chill", year: 1983, plot: "College friends reunite at a funeral, sparking past romances.", location: "South Carolina", time: "day", event: "reunion", characters: ["friends"] },
  { title: "Clue", year: 1985, plot: "Guests meet unexpectedly at a mansion during a murder mystery dinner.", location: "Mansion, USA", time: "evening", event: "social encounter", characters: ["two strangers"] },
  { title: "Arthur", year: 1981, plot: "A wealthy man meets a woman in a nightclub, leading to romance.", location: "New York City", time: "night", event: "social encounter", characters: ["two strangers"] },
  { title: "My Dinner with Andre", year: 1981, plot: "Two old friends meet for a conversation, exploring life and subtle romance.", location: "New York City", time: "evening", event: "reunion", characters: ["friends"] },
  { title: "Local Hero", year: 1983, plot: "A businessman meets a small-town woman while negotiating a corporate deal.", location: "Scotland", time: "day", event: "professional encounter", characters: ["two strangers"] },
  { title: "A Fish Called Wanda", year: 1988, plot: "A thief meets a lawyer while plotting a heist, sparking comedic romance.", location: "London", time: "day", event: "professional encounter", characters: ["two strangers"] },
  { title: "Terms of Endearment", year: 1983, plot: "A widow meets a new man, exploring love and family dynamics.", location: "Houston", time: "day", event: "social encounter", characters: ["two strangers", "family"] },
  { title: "The Sure Thing", year: 1985, plot: "College students meet on a cross-country trip, sparking romantic comedy.", location: "USA", time: "day", event: "road trip encounter", characters: ["two strangers"] },
  { title: "Police Academy", year: 1984, plot: "Cadets meet while training, leading to friendships and romance.", location: "New York City", time: "day", event: "workplace encounter", characters: ["coworkers"] },
  { title: "Mannequin", year: 1987, plot: "A store employee meets a mannequin who comes to life, sparking romance.", location: "Philadelphia", time: "day", event: "magical encounter", characters: ["two strangers"] },
  { title: "The Lonely Guy", year: 1984, plot: "A man meets a woman at a singles bar after a series of comedic mishaps.", location: "New York City", time: "night", event: "social encounter", characters: ["two strangers"] },

  //1990s
  { title: "Pretty Woman", year: 1990, plot: "A businessman’s car gets stuck and a woman helps him, sparking romance.", location: "Beverly Hills", time: "day", event: "street encounter", characters: ["two strangers"] },
  { title: "Four Weddings and a Funeral", year: 1994, plot: "A man falls for a woman while attending several weddings.", location: "London", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Clueless", year: 1995, plot: "A wealthy high school girl meets a new student and sparks romance.", location: "Beverly Hills", time: "day", event: "school encounter", characters: ["students"] },
  { title: "The American President", year: 1995, plot: "The president meets an environmental lobbyist and they fall in love.", location: "Washington D.C.", time: "day", event: "professional encounter", characters: ["two strangers"] },
  { title: "Jerry Maguire", year: 1996, plot: "A sports agent meets a former athlete, sparking romance and personal growth.", location: "New York City", time: "day", event: "workplace encounter", characters: ["two strangers"] },
  { title: "Emma", year: 1996, plot: "A young woman meddles in love and unexpectedly meets her perfect match.", location: "England", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "The Truth About Cats & Dogs", year: 1996, plot: "A radio host meets a man over the phone, sparking mistaken identity romance.", location: "Los Angeles", time: "day", event: "professional encounter", characters: ["two strangers"] },
  { title: "Romeo + Juliet", year: 1996, plot: "Two young lovers meet at a party in modern-day Verona.", location: "Verona, California", time: "evening", event: "social encounter", characters: ["two strangers"] },
  { title: "My Best Friend’s Wedding", year: 1997, plot: "A woman realizes she loves her best friend and tries to win him over.", location: "Chicago", time: "day", event: "reunion", characters: ["friends"] },
  { title: "Chasing Amy", year: 1997, plot: "A comic book artist meets a woman, sparking romance and conflict.", location: "New Jersey", time: "day", event: "professional encounter", characters: ["two strangers"] },
  { title: "Run Lola Run", year: 1998, plot: "A woman meets a man and tries to save him in a time-sensitive adventure.", location: "Berlin", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Sliding Doors", year: 1998, plot: "A woman’s life splits into two paths after missing a train, including romance.", location: "London", time: "day", event: "public encounter", characters: ["two strangers"] },
  { title: "Wild Things", year: 1998, plot: "Two women meet a teacher, sparking intrigue and romantic tension.", location: "Florida", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "The Wedding Singer", year: 1998, plot: "A wedding singer meets a waitress at a reception, igniting romance.", location: "New Jersey", time: "day", event: "wedding encounter", characters: ["two strangers"] },
  { title: "Life is Beautiful", year: 1997, plot: "A man meets his future wife and charms her with humor and kindness.", location: "Italy", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "As Good as It Gets", year: 1997, plot: "A misanthropic man meets a waitress and gradually opens up to love.", location: "New York City", time: "day", event: "public encounter", characters: ["two strangers"] },
  { title: "The Parent Trap", year: 1998, plot: "Twins meet at camp and plot to reunite their divorced parents.", location: "California", time: "day", event: "camp encounter", characters: ["friends", "family"] },
  { title: "Sliding Doors", year: 1998, plot: "Two different timelines show a woman meeting a man in alternate circumstances.", location: "London", time: "day", event: "public encounter", characters: ["two strangers"] },
  { title: "Out of Sight", year: 1998, plot: "A bank robber meets a federal marshal during a heist, sparking romance.", location: "Miami", time: "day", event: "professional encounter", characters: ["two strangers"] },
  { title: "Runaway Bride", year: 1999, plot: "A man meets a woman notorious for leaving men at the altar.", location: "Connecticut", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Teaching Mrs. Tingle", year: 1999, plot: "A student meets a teacher in a darkly comedic school encounter.", location: "Los Angeles", time: "day", event: "school encounter", characters: ["students", "coworkers"] },
  { title: "American Beauty", year: 1999, plot: "A man becomes infatuated with a friend’s daughter, sparking personal and romantic tension.", location: "Suburban USA", time: "day", event: "public encounter", characters: ["two strangers"] },
  { title: "Galaxy Quest", year: 1999, plot: "Actors meet real aliens, sparking adventure and subtle romantic subplots.", location: "Space / USA", time: "day", event: "adventure encounter", characters: ["two strangers"] },
  { title: "Run Lola Run", year: 1998, plot: "Lola meets her boyfriend and must save him from danger.", location: "Berlin", time: "day", event: "public encounter", characters: ["two strangers"] },
  { title: "The Thin Red Line", year: 1998, plot: "Soldiers meet briefly, forming bonds that influence romance and camaraderie.", location: "Pacific island", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "You've Got Mail", year: 1998, plot: "Two business rivals meet online and fall in love unknowingly.", location: "New York City", time: "day", event: "online encounter", characters: ["two strangers"] },

  //2000S
  { title: "The Notebook", year: 2004, plot: "A young couple falls in love during the early 20th century.", location: "North Carolina", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Eternal Sunshine of the Spotless Mind", year: 2004, plot: "A man and woman meet and fall in love, then erase memories of each other.", location: "Long Island", time: "day", event: "public encounter", characters: ["two strangers"] },
  { title: "13 Going on 30", year: 2004, plot: "A girl wakes up as an adult and meets her crush in the corporate world.", location: "New York City", time: "day", event: "workplace encounter", characters: ["two strangers"] },
  { title: "Garden State", year: 2004, plot: "A man returns home and meets a quirky young woman who changes his perspective.", location: "New Jersey", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Bridget Jones’s Diary", year: 2001, plot: "A single woman meets two men, sparking romance and comedic mishaps.", location: "London", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Lost in Translation", year: 2003, plot: "An aging actor meets a young woman in Tokyo, forming a deep connection.", location: "Tokyo", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "The Wedding Planner", year: 2001, plot: "A wedding planner meets the groom of one of her clients.", location: "New York City", time: "day", event: "professional encounter", characters: ["two strangers"] },
  { title: "27 Dresses", year: 2008, plot: "A woman meets a journalist while being bridesmaid at numerous weddings.", location: "New York City", time: "day", event: "wedding encounter", characters: ["two strangers"] },
  { title: "Hitch", year: 2005, plot: "A dating consultant meets a client and helps him navigate romance.", location: "New York City", time: "day", event: "professional encounter", characters: ["two strangers"] },
  { title: "Mean Girls", year: 2004, plot: "A new student meets the popular clique and navigates friendships and crushes.", location: "Illinois", time: "day", event: "school encounter", characters: ["students"] },
  { title: "Juno", year: 2007, plot: "A pregnant teenager meets her baby’s father, forming a unique bond.", location: "Minnesota", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Enchanted", year: 2007, plot: "A fairy-tale princess meets a lawyer in New York City.", location: "New York City", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "A Lot Like Love", year: 2005, plot: "Two people meet on a flight and reconnect over several years.", location: "Various USA", time: "day", event: "travel encounter", characters: ["two strangers"] },
  { title: "Music and Lyrics", year: 2007, plot: "A former pop star meets a songwriter, creating music and romance.", location: "New York City", time: "day", event: "workplace encounter", characters: ["coworkers"] },
  { title: "Knocked Up", year: 2007, plot: "A one-night encounter leads to an unexpected pregnancy.", location: "Los Angeles", time: "night", event: "social encounter", characters: ["two strangers"] },
  { title: "Crazy/Beautiful", year: 2001, plot: "A rich teenager meets a working-class boy, sparking romance and tension.", location: "Los Angeles", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "The Devil Wears Prada", year: 2006, plot: "A young assistant meets her demanding boss, navigating professional and personal growth.", location: "New York City", time: "day", event: "workplace encounter", characters: ["coworkers"] },
  { title: "Napoleon Dynamite", year: 2004, plot: "Two quirky students meet in high school, forming friendship and subtle romance.", location: "Idaho", time: "day", event: "school encounter", characters: ["students"] },
  { title: "The Holiday", year: 2006, plot: "Two women swap homes for the holidays and meet new love interests.", location: "England / Los Angeles", time: "day", event: "travel encounter", characters: ["two strangers"] },
  { title: "Into the Wild", year: 2007, plot: "A young man meets travelers along his journey, forming deep connections.", location: "USA", time: "day", event: "travel encounter", characters: ["two strangers"] },
  { title: "The Pursuit of Happyness", year: 2006, plot: "A man meets a woman while struggling to provide for his family.", location: "San Francisco", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "A Mighty Heart", year: 2007, plot: "A journalist meets his wife, sparking love amid tragedy.", location: "Pakistan / New York", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Little Miss Sunshine", year: 2006, plot: "A family road trip leads to encounters that spark personal and romantic growth.", location: "USA", time: "day", event: "road trip encounter", characters: ["friends", "family"] },
  { title: "Garden State", year: 2004, plot: "A man returns home and meets a quirky young woman.", location: "New Jersey", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Before Sunset", year: 2004, plot: "A couple reunites in Paris after many years, sharing one afternoon together.", location: "Paris", time: "afternoon", event: "reunion", characters: ["two strangers"] },

  //2010s
  { title: "The Big Sick", year: 2017, plot: "A comedian meets a graduate student, sparking love complicated by cultural expectations.", location: "Chicago", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Love, Simon", year: 2018, plot: "A teenager navigates high school while secretly falling for a classmate online.", location: "Atlanta", time: "day", event: "online encounter", characters: ["students", "two strangers"] },
  { title: "To All the Boys I’ve Loved Before", year: 2018, plot: "A girl’s private letters are exposed, bringing her close to her crush.", location: "Seattle", time: "day", event: "school encounter", characters: ["students"] },
  { title: "Brooklyn", year: 2015, plot: "A young Irish immigrant meets a charming man in New York City.", location: "New York City", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "The Fault in Our Stars", year: 2014, plot: "Two teens meet at a cancer support group and fall in love.", location: "Indianapolis / Amsterdam", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "About Time", year: 2013, plot: "A man discovers he can time travel and meets the woman of his dreams.", location: "London", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "The Spectacular Now", year: 2013, plot: "Two high school seniors meet at a party and form a romantic bond.", location: "Midwest USA", time: "evening", event: "social encounter", characters: ["students"] },
  { title: "Begin Again", year: 2013, plot: "A musician and a singer-songwriter meet and collaborate in New York City.", location: "New York City", time: "day", event: "workplace encounter", characters: ["two strangers"] },
  { title: "Silver Linings Playbook", year: 2012, plot: "Two people struggling with personal issues meet at a therapy group.", location: "Philadelphia", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Midnight in Paris", year: 2011, plot: "A writer meets historical figures in Paris during magical midnight encounters.", location: "Paris", time: "night", event: "magical encounter", characters: ["two strangers"] },
  { title: "Crazy, Stupid, Love", year: 2011, plot: "A man meets a dating coach after his marriage falls apart.", location: "Los Angeles", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Friends with Benefits", year: 2011, plot: "Two friends decide to add romance to their friendship.", location: "New York City", time: "day", event: "social encounter", characters: ["friends"] },
  { title: "The Vow", year: 2012, plot: "A man works to win back his wife after she loses her memory in an accident.", location: "Chicago", time: "day", event: "reunion", characters: ["spouses"] },
  { title: "Warm Bodies", year: 2013, plot: "A zombie meets a living girl, sparking an unlikely romance.", location: "Post-apocalyptic city", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Obvious Child", year: 2014, plot: "A woman meets a man after an unexpected life event, leading to romance.", location: "New York City", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Love, Rosie", year: 2014, plot: "Childhood friends navigate missed opportunities and eventual romance.", location: "Dublin", time: "day", event: "friend encounter", characters: ["friends"] },
  { title: "Me Before You", year: 2016, plot: "A caregiver meets her quadriplegic charge and sparks romance.", location: "England", time: "day", event: "workplace encounter", characters: ["two strangers"] },
  { title: "Set It Up", year: 2018, plot: "Two assistants meet while scheming to set up their bosses.", location: "New York City", time: "day", event: "workplace encounter", characters: ["coworkers"] },
  { title: "The Incredible Jessica James", year: 2017, plot: "A playwright meets a man while navigating life after a breakup.", location: "New York City", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Palm Springs", year: 2020, plot: "Two wedding guests meet and relive the same day repeatedly.", location: "Palm Springs", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "The Half of It", year: 2020, plot: "A shy student helps a classmate woo a girl they both like.", location: "Small town, USA", time: "day", event: "school encounter", characters: ["students"] },
  { title: "To All the Boys: P.S. I Still Love You", year: 2020, plot: "A girl navigates her relationship after letters bring new complications.", location: "Seattle", time: "day", event: "school encounter", characters: ["students"] },
  { title: "Yesterday", year: 2019, plot: "A musician meets a fan who remembers a world without The Beatles.", location: "London", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Long Shot", year: 2019, plot: "A journalist reconnects with a former babysitter who is now a politician.", location: "Washington D.C.", time: "day", event: "reunion", characters: ["two strangers"] },
  { title: "Isn’t It Romantic", year: 2019, plot: "A woman wakes up in a rom-com universe and meets a charming man.", location: "New York City", time: "day", event: "magical encounter", characters: ["two strangers"] },
  { title: "Always Be My Maybe", year: 2019, plot: "Childhood friends meet again as adults and rediscover romance.", location: "San Francisco", time: "day", event: "reunion", characters: ["friends"] },
  { title: "Marriage Story", year: 2019, plot: "A couple navigates separation, love, and connection amidst divorce.", location: "New York City / Los Angeles", time: "day", event: "social encounter", characters: ["spouses"] },
  { title: "Yesterday", year: 2019, plot: "A musician meets his love interest while navigating fame in a Beatles-less world.", location: "London", time: "day", event: "social encounter", characters: ["two strangers"] },

  //2020s
  { title: "Palm Springs", year: 2020, plot: "Two wedding guests meet and relive the same day repeatedly.", location: "Palm Springs", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "The Half of It", year: 2020, plot: "A shy student helps a classmate woo a girl they both like.", location: "Small town, USA", time: "day", event: "school encounter", characters: ["students"] },
  { title: "To All the Boys: P.S. I Still Love You", year: 2020, plot: "A girl navigates her relationship after letters bring new complications.", location: "Seattle", time: "day", event: "school encounter", characters: ["students"] },
  { title: "Marry Me", year: 2022, plot: "A pop star meets a stranger in the audience and impulsively marries him.", location: "New York City", time: "day", event: "public encounter", characters: ["two strangers"] },
  { title: "Ticket to Paradise", year: 2022, plot: "Exes meet on a tropical island while trying to stop their daughter’s wedding.", location: "Bali", time: "day", event: "family encounter", characters: ["two strangers", "family"] },
  { title: "Love Hard", year: 2021, plot: "A woman meets her online crush in person, only to discover he catfished her.", location: "Los Angeles", time: "day", event: "online encounter", characters: ["two strangers"] },
  { title: "Resort to Love", year: 2021, plot: "A singer meets her ex-fiancé at a luxury resort.", location: "Mauritius", time: "day", event: "reunion", characters: ["two strangers"] },
  { title: "Your Place or Mine", year: 2023, plot: "Two friends swap homes for a week, realizing their romantic feelings.", location: "Los Angeles / New York City", time: "day", event: "friend encounter", characters: ["friends"] },
  { title: "Shotgun Wedding", year: 2022, plot: "A couple’s destination wedding is hijacked, leading to romance and chaos.", location: "Dominican Republic", time: "day", event: "wedding encounter", characters: ["two strangers"] },
  { title: "Bros", year: 2022, plot: "Two men meet on a dating app and navigate love and friendship.", location: "New York City", time: "day", event: "online encounter", characters: ["two strangers"] },
  { title: "Ticket to Paradise", year: 2022, plot: "Exes meet again on a tropical island while trying to sabotage a wedding.", location: "Bali", time: "day", event: "family encounter", characters: ["two strangers", "family"] },
  { title: "Marry Me", year: 2022, plot: "A pop star impulsively marries a man in the audience, leading to romance.", location: "New York City", time: "day", event: "public encounter", characters: ["two strangers"] },
  { title: "Love, Weddings & Other Disasters", year: 2020, plot: "Multiple couples meet at weddings, sparking romance and comedy.", location: "Los Angeles", time: "day", event: "wedding encounter", characters: ["two strangers"] },
  { title: "Purple Hearts", year: 2022, plot: "A struggling musician marries a Marine to get benefits, sparking love.", location: "California", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "Happiest Season", year: 2020, plot: "A woman meets her girlfriend’s family for Christmas, navigating love and acceptance.", location: "Philadelphia", time: "day", event: "family encounter", characters: ["two strangers", "family"] },
  { title: "Your Place or Mine", year: 2023, plot: "Two friends swap homes for a week and realize they love each other.", location: "Los Angeles / New York City", time: "day", event: "friend encounter", characters: ["friends"] },
  { title: "Plan B", year: 2021, plot: "A teen meets her best friend while navigating a surprising pregnancy.", location: "USA", time: "day", event: "friend encounter", characters: ["friends"] },
  { title: "The Lost City", year: 2022, plot: "A novelist meets a cover model in a jungle adventure.", location: "South America", time: "day", event: "adventure encounter", characters: ["two strangers"] },
  { title: "Love Hard", year: 2021, plot: "A woman meets her online crush and navigates love after discovering his deception.", location: "Los Angeles", time: "day", event: "online encounter", characters: ["two strangers"] },
  { title: "Marry Me", year: 2022, plot: "A celebrity and a stranger marry impulsively during a concert.", location: "New York City", time: "day", event: "public encounter", characters: ["two strangers"] },
  { title: "Resort to Love", year: 2021, plot: "A singer meets her ex-fiancé while performing at a resort.", location: "Mauritius", time: "day", event: "reunion", characters: ["two strangers"] },
  { title: "Bros", year: 2022, plot: "Two men meet via a dating app and navigate love and social dynamics.", location: "New York City", time: "day", event: "online encounter", characters: ["two strangers"] },
  { title: "Ticket to Paradise", year: 2022, plot: "Exes meet while trying to prevent their daughter’s wedding.", location: "Bali", time: "day", event: "family encounter", characters: ["two strangers", "family"] },
  { title: "Your Place or Mine", year: 2023, plot: "Friends swap homes and realize their romantic feelings.", location: "Los Angeles / New York City", time: "day", event: "friend encounter", characters: ["friends"] },
  { title: "Happiest Season", year: 2020, plot: "A woman meets her girlfriend’s family at Christmas.", location: "Philadelphia", time: "day", event: "family encounter", characters: ["two strangers", "family"] },
  { title: "Purple Hearts", year: 2022, plot: "A Marine and musician marry for convenience, discovering love.", location: "California", time: "day", event: "social encounter", characters: ["two strangers"] },
  { title: "The Lost City", year: 2022, plot: "A novelist meets her cover model during a jungle adventure.", location: "South America", time: "day", event: "adventure encounter", characters: ["two strangers"] },
  { title: "Plan B", year: 2021, plot: "Two friends navigate unexpected pregnancy and romance.", location: "USA", time: "day", event: "friend encounter", characters: ["friends"] },
  { title: "Love, Weddings & Other Disasters", year: 2020, plot: "Multiple couples meet at weddings, sparking romance and comedy.", location: "Los Angeles", time: "day", event: "wedding encounter", characters: ["two strangers"] },

  //Additions
];

// Example to quickly generate placeholders
for(let i=12; i<=200; i++){
  movies.push({
    title: `Movie ${i}`,
    year: 1980 + (i % 40),
    plot: `Plot description for Movie ${i}, including events, romance, or friendship.`,
    location: ["Paris","London","New York","Los Angeles","Tokyo","Rome","Berlin"][i%7],
    time: ["morning","afternoon","evening","night"][i%4],
    event: ["chance encounter","coffee spill","party","walk","meeting","reunion"][i%6],
    characters: [["two strangers"], ["friends"], ["coworkers"], ["family"]][i%4]
  });
}
